"""core schema

Revision ID: 4add8674d4f0
Revises:
Create Date: 2026-08-20 15:12:35.116423
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4add8674d4f0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any table declares a vector column. On Liara
    # the extension is enabled from the panel before data exists (enabling it
    # restarts the database); locally the pgvector image ships it. IF NOT
    # EXISTS keeps one migration correct in both places.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("source_repo_url", sa.String(length=512), nullable=False),
        sa.Column("source_branch", sa.String(length=128), nullable=False),
        sa.Column("source_commit", sa.String(length=64), nullable=False),
        sa.Column("ingest_sections", sa.String(length=512), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("normalizer_version", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('building', 'validating', 'ready', 'active', 'superseded', 'failed')",
            name=op.f("ck_index_versions_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_versions")),
    )
    op.create_index(
        "uq_index_versions_active",
        "index_versions",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active IS TRUE"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("client_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("initial_question", sa.Text(), nullable=False),
        sa.Column("initial_question_normalized", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("technical_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rescue_tool", sa.String(length=16), nullable=True),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_conversations_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_session_id"), "conversations", ["session_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index_version_id", sa.UUID(), nullable=False),
        sa.Column("source_path", sa.String(length=512), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_commit", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("section", sa.String(length=128), nullable=False),
        sa.Column("breadcrumbs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=True),
        sa.Column("runtime", sa.String(length=128), nullable=True),
        sa.Column("framework", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_char_count", sa.Integer(), nullable=False),
        sa.Column("discarded_char_ratio", sa.Float(), nullable=False),
        sa.Column("flagged_for_review", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_documents_index_version_id_index_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "index_version_id", "source_path", name="uq_documents_index_source_path"
        ),
    )
    op.create_index(
        op.f("ix_documents_index_version_id"), "documents", ["index_version_id"], unique=False
    )
    op.create_index(
        "ix_documents_index_version_id_content_hash",
        "documents",
        ["index_version_id", "content_hash"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index_version_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_normalized", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', text_normalized)", persisted=True),
            nullable=True,
        ),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_path", sa.String(length=512), nullable=False),
        sa.Column("source_commit", sa.String(length=64), nullable=False),
        sa.Column("heading_anchor", sa.String(length=256), nullable=True),
        sa.Column("section_title", sa.Text(), nullable=True),
        sa.Column("breadcrumbs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_type", sa.String(length=16), nullable=False),
        sa.Column("code_languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=True),
        sa.Column("runtime", sa.String(length=128), nullable=True),
        sa.Column("framework", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('prose', 'code', 'step', 'table', 'mixed')",
            name=op.f("ck_document_chunks_content_type"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_document_chunks_index_version_id_index_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "ordinal", name="uq_document_chunks_document_id_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_index_version_id"),
        "document_chunks",
        ["index_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_search_vector",
        "document_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("question_normalized", sa.Text(), nullable=False),
        sa.Column("presented_faq_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('resolved', 'unresolved')", name=op.f("ck_feedback_outcome")
        ),
        sa.CheckConstraint("stage IN ('faq', 'chat')", name=op.f("ck_feedback_stage")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_feedback_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_feedback_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_index(
        op.f("ix_feedback_conversation_id"), "feedback", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_feedback_session_id"), "feedback", ["session_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("index_version_id", sa.UUID(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'tool', 'system')", name=op.f("ck_messages_role")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_messages_index_version_id_index_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "ordinal", name="uq_messages_conversation_id_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "faq_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("question_normalized", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("source_chunk_id", sa.UUID(), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("heading_anchor", sa.String(length=256), nullable=True),
        sa.Column("source_commit", sa.String(length=64), nullable=True),
        sa.Column("source_content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('generated', 'reviewed', 'rejected')", name=op.f("ck_faq_items_status")
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_faq_items_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_faq_items_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faq_items")),
    )
    op.create_index(
        op.f("ix_faq_items_source_document_id"), "faq_items", ["source_document_id"], unique=False
    )
    op.create_index(
        "ix_faq_items_status_is_active", "faq_items", ["status", "is_active"], unique=False
    )
    op.create_table(
        "image_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index_version_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("heading_anchor", sa.String(length=256), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_image_assets_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_image_assets_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_image_assets_index_version_id_index_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_assets")),
        sa.UniqueConstraint(
            "index_version_id", "document_id", "url", "ordinal", name="uq_image_assets_identity"
        ),
    )
    op.create_index(op.f("ix_image_assets_chunk_id"), "image_assets", ["chunk_id"], unique=False)
    op.create_index(
        op.f("ix_image_assets_document_id"), "image_assets", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_assets_index_version_id"), "image_assets", ["index_version_id"], unique=False
    )
    op.create_table(
        "request_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("transitions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("stream_key", sa.String(length=128), nullable=True),
        sa.Column("last_delivered_offset", sa.String(length=64), nullable=True),
        sa.Column("result_message_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'retrieving', 'generating', 'retrying', 'completed', 'failed')",
            name=op.f("ck_request_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_request_jobs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result_message_id"],
            ["messages.id"],
            name=op.f("fk_request_jobs_result_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_request_jobs_idempotency_key"),
    )
    op.create_index(
        op.f("ix_request_jobs_conversation_id"), "request_jobs", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_request_jobs_status_created_at", "request_jobs", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_request_jobs_trace_id"), "request_jobs", ["trace_id"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("index_version_id", sa.UUID(), nullable=True),
        sa.Column("faq_item_id", sa.UUID(), nullable=True),
        sa.Column("rescue_tool", sa.String(length=16), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('faq_impression', 'faq_selection', 'faq_resolution', 'rescue_tool_transition', 'retrieval', 'generation', 'provider_fallback', 'job_outcome', 'error', 'ingestion')",
            name=op.f("ck_usage_events_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_usage_events_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["faq_item_id"],
            ["faq_items.id"],
            name=op.f("fk_usage_events_faq_item_id_faq_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["index_version_id"],
            ["index_versions.id"],
            name=op.f("fk_usage_events_index_version_id_index_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["request_jobs.id"],
            name=op.f("fk_usage_events_job_id_request_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_usage_events_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_index(
        op.f("ix_usage_events_conversation_id"), "usage_events", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_usage_events_error_code_created_at",
        "usage_events",
        ["error_code", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_events_event_type_created_at",
        "usage_events",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_usage_events_job_id"), "usage_events", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_usage_events_session_id"), "usage_events", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_usage_events_trace_id"), "usage_events", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_events_trace_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_session_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_job_id"), table_name="usage_events")
    op.drop_index("ix_usage_events_event_type_created_at", table_name="usage_events")
    op.drop_index("ix_usage_events_error_code_created_at", table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_conversation_id"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_request_jobs_trace_id"), table_name="request_jobs")
    op.drop_index("ix_request_jobs_status_created_at", table_name="request_jobs")
    op.drop_index(op.f("ix_request_jobs_conversation_id"), table_name="request_jobs")
    op.drop_table("request_jobs")
    op.drop_index(op.f("ix_image_assets_index_version_id"), table_name="image_assets")
    op.drop_index(op.f("ix_image_assets_document_id"), table_name="image_assets")
    op.drop_index(op.f("ix_image_assets_chunk_id"), table_name="image_assets")
    op.drop_table("image_assets")
    op.drop_index("ix_faq_items_status_is_active", table_name="faq_items")
    op.drop_index(op.f("ix_faq_items_source_document_id"), table_name="faq_items")
    op.drop_table("faq_items")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_feedback_session_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_conversation_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(
        "ix_document_chunks_search_vector", table_name="document_chunks", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_document_chunks_index_version_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_documents_index_version_id_content_hash", table_name="documents")
    op.drop_index(op.f("ix_documents_index_version_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversations_session_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("sessions")
    op.drop_index(
        "uq_index_versions_active",
        table_name="index_versions",
        postgresql_where=sa.text("is_active IS TRUE"),
    )
    op.drop_table("index_versions")
    # ### end Alembic commands ###
