"""runtime settings overrides

Revision ID: 9a26e36a7b99
Revises: dbd77a4b7a1e
Create Date: 2026-08-21 08:23:27.187943

Autogenerate proposed dropping `ix_document_chunks_embedding_hnsw` and
`ix_faq_items_embedding_hnsw` in this revision. Those drops were removed by
hand and must not be reintroduced.

Alembic cannot read a pgvector index: it compares the reflected definition
against the model, sees no `vector_cosine_ops` opclass it recognizes on either
side, and concludes the index is surplus. Applying that would drop both HNSW
indexes and silently degrade every similarity query to a sequential scan —
slower, but still correct, so nothing would fail and nobody would be paged.

**Any future autogenerated revision will propose the same two drops.** Delete
them before applying, every time.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9a26e36a7b99"
down_revision: str | None = "dbd77a4b7a1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "runtime_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runtime_settings")),
    )
    op.create_index(op.f("ix_runtime_settings_key"), "runtime_settings", ["key"], unique=True)


def downgrade() -> None:
    op.drop_index(op.f("ix_runtime_settings_key"), table_name="runtime_settings")
    op.drop_table("runtime_settings")
